# Nombre del servidor
spring.application.name=baratito-server

# 1. Conexión a la base de datos de Docker
# localhost:5433 es donde está escuchando el contenedor de Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/baratito_db
spring.datasource.username=postgres
spring.datasource.password=123123
spring.datasource.driver-className=org.postgresql.Driver

# 2. Configuración de JPA / Hibernate
# 'update' hace que Spring cree las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Puerto del Backend
server.port=8080